apiVersion: certmanager.k8s.io/v1aplha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'green@ukr.net'
    privateKeySecretRef:
      name: letsencrypt-prod
      http01: {}